server:
  port: 0  # Que el puerto sea aleatorio si usás balanceador

spring:
  datasource:
    url: jdbc:postgresql://postgres_administracion:5432/administraciondb
    username: admin_user
    password: admin_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
